#!/usr/bin/env bash

if [ -f data/processed/subunits.json ]
  then
    rm data/processed/subunits.json
fi

ogr2ogr -f GeoJSON data/processed/subunits.json data/unprocessed/MajorRoads.shp

if [ -f data/processed/subunits.json ]
  then
    topojson -o data/processed/roads.json data/processed/subunits.json
fi

if [ -f data/processed/subunits.json ]
  then
    rm data/processed/subunits.json
fi
