#!/usr/bin/env bash

if [ -f data/processed/subunits.json ]
  then
    rm data/processed/subunits.json
fi

ogr2ogr -f GeoJSON -where "TYPE IN ('primary', 'secondary', 'tertiary')" data/processed/subunits.json data/unprocessed/south_australia_highway.shp -clipsrc 138.57 -34.945 138.64 -34.88

if [ -f data/processed/subunits.json ]
  then
    topojson -o data/processed/roads.json data/processed/subunits.json
fi

if [ -f data/processed/subunits.json ]
  then
    rm data/processed/subunits.json
fi
